<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSINLT-647" ignored="6" name="Default test" tests="4" failures="1" timestamp="2020-12-30T12:29:46 IST" time="13.332" errors="0">
  <testcase name="loginAsBankManager" time="2.259" classname="com.learning.testcases.BankManagerLoginTest">
    <failure type="java.lang.AssertionError" message="Bank Manager Login failed">
      <![CDATA[java.lang.AssertionError: Bank Manager Login failed
at org.testng.Assert.fail(Assert.java:99)
at com.learning.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginAsBankManager -->
  <testcase name="addCustomer" time="4.065" classname="com.learning.testcases.AddCustomerTest"/>
  <testcase name="addCustomer" time="3.444" classname="com.learning.testcases.AddCustomerTest"/>
  <testcase name="addCustomer" time="3.514" classname="com.learning.testcases.AddCustomerTest"/>
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase name="@BeforeSuite setup" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase name="@BeforeSuite setup" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase name="@BeforeSuite setup" time="0.0" classname="com.learning.base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Default test -->
